//
//  FabricaCeldas.h
//  Custom Table View
//
//  Created by Lorenzo Villarroel on 17/07/12.
//  Copyright (c) 201ELMUNDO __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>

#define UNSELECTEDCOLORAPARIENCIAAULATITULO [UIColor colorWithRed:(215.0/255.0) green:(214.0/255.0) blue:(211.0/255.0) alpha:1.0]
#define SELECTEDCOLORAPARIENCIAAULATITULO [UIColor colorWithRed:(133/255.0) green:(163/255.0) blue:(206/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIAAULATITULO [UIColor colorWithRed:(102/255.0) green:(102/255.0) blue:(100/255.0) alpha:1]
#define TEXTSELECTEDCOLORAPARIENCIAAULATITULO [UIColor whiteColor]
#define UNSELECTEDFONTAPARIENCIAAULATITULO [UIFont boldSystemFontOfSize:16.0]
#define SELECTEDFONTAPARIENCIAAULATITULO [UIFont boldSystemFontOfSize:16.0]
#define BORDERCOLORAULATITULO [UIColor colorWithRed:(215.0/255.0) green:(214.0/255.0) blue:(211.0/255.0) alpha:1.0]
#define BORDERWIDTHAULATITULO 0.8
#define CORNERRADIUSAULATITULO 0
#define TEXTALIGNMENTAULATITULO NSTextAlignmentCenter
#define ACCESORYTYPEAULATITULO UITableViewCellAccessoryNone
#define LINEBREAKMODEAULATITULO UILineBreakModeWordWrap
#define NUMBEROFLINESAULATITULO 0
#define ACCESORYVIEWAULATITULO nil
#define HEIGHTCELLAULATITULO 60

#define APARIENCIAAULATITULO [[CustomCellAppearance alloc] initWithAppearanceWithUnselectedColor:UNSELECTEDCOLORAPARIENCIAAULATITULO selectedColor:SELECTEDCOLORAPARIENCIAAULATITULO unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIAAULATITULO selectedTextColor:TEXTSELECTEDCOLORAPARIENCIAAULATITULO unselectedTextFont:UNSELECTEDFONTAPARIENCIAAULATITULO selectedTextFont:SELECTEDFONTAPARIENCIAAULATITULO borderColor:BORDERCOLORAULATITULO borderWidth:BORDERWIDTHAULATITULO cornerRadius:CORNERRADIUSAULATITULO textAlignment:TEXTALIGNMENTAULATITULO accesoryType:ACCESORYTYPEAULATITULO lineBreakMode:LINEBREAKMODEAULATITULO numberOfLines:NUMBEROFLINESAULATITULO accesoryView:ACCESORYVIEWAULATITULO heightCell:HEIGHTCELLAULATITULO]


#define UNSELECTEDCOLORAPARIENCIAAULA [UIColor whiteColor]
#define SELECTEDCOLORAPARIENCIAAULA [UIColor colorWithRed:(133/255.0) green:(163/255.0) blue:(206/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIAAULA [UIColor colorWithRed:(102/255.0) green:(102/255.0) blue:(100/255.0) alpha:1]
#define TEXTSELECTEDCOLORAPARIENCIAAULA [UIColor whiteColor]
#define UNSELECTEDFONTAPARIENCIAAULA [UIFont systemFontOfSize:18.0]
#define SELECTEDFONTAPARIENCIAAULA [UIFont systemFontOfSize:18.0]
#define BORDERCOLORAULA [UIColor colorWithRed:(56/255.0) green:(115/255.0) blue:(194/255.0) alpha:1.0] 
#define BORDERWIDTHAULA 0.8
#define CORNERRADIUSAULA 0
#define TEXTALIGNMENTAULA NSTextAlignmentLeft
#define ACCESORYTYPEAULA UITableViewCellAccessoryNone
#define LINEBREAKMODEAULA NSLineBreakByWordWrapping
#define NUMBEROFLINESAULA 0
#define ACCESORYVIEWAULA nil
#define HEIGHTCELLAULA 47

#define APARIENCIAAULA [[CustomCellAppearance alloc] initWithAppearanceWithUnselectedColor:UNSELECTEDCOLORAPARIENCIAAULA selectedColor:SELECTEDCOLORAPARIENCIAAULA unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIAAULA selectedTextColor:TEXTSELECTEDCOLORAPARIENCIAAULA unselectedTextFont:UNSELECTEDFONTAPARIENCIAAULA selectedTextFont:SELECTEDFONTAPARIENCIAAULA borderColor:BORDERCOLORAULA borderWidth:BORDERWIDTHAULA cornerRadius:CORNERRADIUSAULA textAlignment:TEXTALIGNMENTAULA accesoryType:ACCESORYTYPEAULA lineBreakMode:LINEBREAKMODEAULA numberOfLines:NUMBEROFLINESAULA accesoryView:ACCESORYVIEWAULA heightCell:HEIGHTCELLAULA]


#define UNSELECTEDCOLORAPARIENCIAELMUNDOPEQUENO [UIColor whiteColor]
#define SELECTEDCOLORAPARIENCIAELMUNDOPEQUENO [UIColor colorWithRed:(71/255.0) green:(105/255.0) blue:(153/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIAELMUNDOPEQUENO [UIColor blackColor]
#define TEXTSELECTEDCOLORAPARIENCIAELMUNDOPEQUENO [UIColor whiteColor]
#define UNSELECTEDFONTAPARIENCIAELMUNDOPEQUENO [UIFont systemFontOfSize:16.0]
#define SELECTEDFONTAPARIENCIAELMUNDOPEQUENO [UIFont systemFontOfSize:16.0]
#define BORDERCOLORELMUNDOPEQUENO [UIColor blackColor]
#define BORDERWIDTHELMUNDOPEQUENO 0.8
#define CORNERRADIUSELMUNDOPEQUENO 0
#define TEXTALIGNMENTELMUNDOPEQUENO NSTextAlignmentLeft
#define ACCESORYTYPEELMUNDOPEQUENO UITableViewCellAccessoryDisclosureIndicator
#define LINEBREAKMODEELMUNDOPEQUENO NSLineBreakByWordWrapping
#define NUMBEROFLINESELMUNDOPEQUENO 0
#define ACCESORYVIEWELMUNDOPEQUENO nil
#define HEIGHTCELLELMUNDOPEQUENO 44

#define APARIENCIAELMUNDOPEQUENO [[CustomCellAppearance alloc] initWithAppearanceWithUnselectedColor:UNSELECTEDCOLORAPARIENCIAELMUNDOPEQUENO selectedColor:SELECTEDCOLORAPARIENCIAELMUNDOPEQUENO unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIAELMUNDOPEQUENO selectedTextColor:TEXTSELECTEDCOLORAPARIENCIAELMUNDOPEQUENO unselectedTextFont:UNSELECTEDFONTAPARIENCIAELMUNDOPEQUENO selectedTextFont:SELECTEDFONTAPARIENCIAELMUNDOPEQUENO borderColor:BORDERCOLORELMUNDOPEQUENO borderWidth:BORDERWIDTHELMUNDOPEQUENO cornerRadius:CORNERRADIUSELMUNDOPEQUENO textAlignment:TEXTALIGNMENTELMUNDOPEQUENO accesoryType:ACCESORYTYPEELMUNDOPEQUENO lineBreakMode:LINEBREAKMODEELMUNDOPEQUENO numberOfLines:NUMBEROFLINESELMUNDOPEQUENO accesoryView:ACCESORYVIEWELMUNDOPEQUENO heightCell:HEIGHTCELLELMUNDOPEQUENO]

#define UNSELECTEDCOLORAPARIENCIAELMUNDOGRANDE [UIColor whiteColor]
#define SELECTEDCOLORAPARIENCIAELMUNDOGRANDE [UIColor colorWithRed:(71/255.0) green:(105/255.0) blue:(153/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIAELMUNDOGRANDE [UIColor blackColor]
#define TEXTSELECTEDCOLORAPARIENCIAELMUNDOGRANDE [UIColor whiteColor]
#define UNSELECTEDFONTAPARIENCIAELMUNDOGRANDE [UIFont systemFontOfSize:16.0]
#define SELECTEDFONTAPARIENCIAELMUNDOGRANDE [UIFont systemFontOfSize:16.0]
#define BORDERCOLORELMUNDOGRANDE [UIColor blackColor]
#define BORDERWIDTHELMUNDOGRANDE 0.8
#define CORNERRADIUSELMUNDOGRANDE 0
#define TEXTALIGNMENTELMUNDOGRANDE NSTextAlignmentLeft
#define ACCESORYTYPEELMUNDOGRANDE UITableViewCellAccessoryDisclosureIndicator
#define LINEBREAKMODEELMUNDOGRANDE NSLineBreakByWordWrapping
#define NUMBEROFLINESELMUNDOGRANDE 0
#define ACCESORYVIEWELMUNDOGRANDE nil
#define HEIGHTCELLELMUNDOGRANDE 52

#define APARIENCIAELMUNDOGRANDE [[CustomCellAppearance alloc] initWithAppearanceWithUnselectedColor:UNSELECTEDCOLORAPARIENCIAELMUNDOGRANDE selectedColor:SELECTEDCOLORAPARIENCIAELMUNDOGRANDE unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIAELMUNDOGRANDE selectedTextColor:TEXTSELECTEDCOLORAPARIENCIAELMUNDOGRANDE unselectedTextFont:UNSELECTEDFONTAPARIENCIAELMUNDOGRANDE selectedTextFont:SELECTEDFONTAPARIENCIAELMUNDOGRANDE borderColor:BORDERCOLORELMUNDOGRANDE borderWidth:BORDERWIDTHELMUNDOGRANDE cornerRadius:CORNERRADIUSELMUNDOGRANDE textAlignment:TEXTALIGNMENTELMUNDOGRANDE accesoryType:ACCESORYTYPEELMUNDOGRANDE lineBreakMode:LINEBREAKMODEELMUNDOGRANDE numberOfLines:NUMBEROFLINESELMUNDOGRANDE accesoryView:ACCESORYVIEWELMUNDOGRANDE heightCell:HEIGHTCELLELMUNDOGRANDE]


#define UNSELECTEDCOLORAPARIENCIAELMUNDOCUENTA [UIColor whiteColor]
#define SELECTEDCOLORAPARIENCIAELMUNDOCUENTA [UIColor whiteColor]
#define TEXTUNSELECTEDCOLORAPARIENCIAELMUNDOCUENTA [UIColor blackColor]
#define TEXTSELECTEDCOLORAPARIENCIAELMUNDOCUENTA [UIColor blackColor]
#define UNSELECTEDFONTAPARIENCIAELMUNDOCUENTA [UIFont systemFontOfSize:16.0]
#define SELECTEDFONTAPARIENCIAELMUNDOCUENTA [UIFont systemFontOfSize:16.0]
#define BORDERCOLORELMUNDOCUENTA [UIColor blackColor]
#define BORDERWIDTHELMUNDOCUENTA 0.8
#define CORNERRADIUSELMUNDOCUENTA 0
#define TEXTALIGNMENTELMUNDOCUENTA NSTextAlignmentLeft
#define ACCESORYTYPEELMUNDOCUENTA UITableViewCellAccessoryNone
#define LINEBREAKMODEELMUNDOCUENTA NSLineBreakByWordWrapping
#define NUMBEROFLINESELMUNDOCUENTA 0
#define ACCESORYVIEWELMUNDOCUENTA nil
#define HEIGHTCELLELMUNDOCUENTA 44

#define APARIENCIAELMUNDOCUENTA [[CustomCellAppearance alloc] initWithAppearanceWithUnselectedColor:UNSELECTEDCOLORAPARIENCIAELMUNDOCUENTA selectedColor:SELECTEDCOLORAPARIENCIAELMUNDOCUENTA unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIAELMUNDOCUENTA selectedTextColor:TEXTSELECTEDCOLORAPARIENCIAELMUNDOCUENTA unselectedTextFont:UNSELECTEDFONTAPARIENCIAELMUNDOCUENTA selectedTextFont:SELECTEDFONTAPARIENCIAELMUNDOCUENTA borderColor:BORDERCOLORELMUNDOCUENTA borderWidth:BORDERWIDTHELMUNDOCUENTA cornerRadius:CORNERRADIUSELMUNDOCUENTA textAlignment:TEXTALIGNMENTELMUNDOCUENTA accesoryType:ACCESORYTYPEELMUNDOCUENTA lineBreakMode:LINEBREAKMODEELMUNDOCUENTA numberOfLines:NUMBEROFLINESELMUNDOCUENTA accesoryView:ACCESORYVIEWELMUNDOCUENTA heightCell:HEIGHTCELLELMUNDOCUENTA]



#define SELECTEDCOLORAPARIENCIALISTADOCAPITULOS [UIColor colorWithRed:(133/255.0) green:(163/255.0) blue:(206/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIALISTADOCAPITULOS nil
#define TEXTSELECTEDCOLORAPARIENCIALISTADOCAPITULOS nil
#define UNSELECTEDFONTAPARIENCIALISTADOCAPITULOS nil
#define SELECTEDFONTAPARIENCIALISTADOCAPITULOS nil
#define TEXTALIGNMENTLISTADOCAPITULOS 0
#define ACCESORYTYPELISTADOCAPITULOS UITableViewCellAccessoryNone
#define LINEBREAKMODELISTADOCAPITULOS 0
#define NUMBEROFLINESLISTADOCAPITULOS 0
#define ACCESORYVIEWLISTADOCAPITULOS nil
//#define CUSTOMHEIGHTCELLLISTADOCAPITULOS 80

#define APARIENCIALISTADOCAPITULOS(BACKGROUNDVIEW,HEIGHTCELL) [[CustomCellAppearance alloc] initWithAppearanceWithCustomBackgroundViewWithSelectedColor:SELECTEDCOLORAPARIENCIALISTADOCAPITULOS unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIALISTADOCAPITULOS selectedTextColor:TEXTSELECTEDCOLORAPARIENCIALISTADOCAPITULOS unselectedTextFont:UNSELECTEDFONTAPARIENCIALISTADOCAPITULOS selectedTextFont:SELECTEDFONTAPARIENCIALISTADOCAPITULOS textAlignment:TEXTALIGNMENTLISTADOCAPITULOS accesoryType:ACCESORYTYPELISTADOCAPITULOS lineBreakMode:LINEBREAKMODELISTADOCAPITULOS numberOfLines:NUMBEROFLINESLISTADOCAPITULOS accesoryView:ACCESORYVIEWLISTADOCAPITULOS backgroundView:BACKGROUNDVIEW heightCell:HEIGHTCELL]

#define SELECTEDCOLORAPARIENCIAMASTERTABLEVIEW [UIColor colorWithRed:(133/255.0) green:(163/255.0) blue:(206/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIAMASTERTABLEVIEW nil
#define TEXTSELECTEDCOLORAPARIENCIAMASTERTABLEVIEW nil
#define UNSELECTEDFONTAPARIENCIAMASTERTABLEVIEW nil
#define SELECTEDFONTAPARIENCIAMASTERTABLEVIEW nil
#define TEXTALIGNMENTMASTERTABLEVIEW 0
#define ACCESORYTYPEMASTERTABLEVIEW UITableViewCellAccessoryNone
#define LINEBREAKMODEMASTERTABLEVIEW 0
#define NUMBEROFLINESMASTERTABLEVIEW 0
#define ACCESORYVIEWMASTERTABLEVIEW nil
//#define CUSTOMHEIGHTCELLMASTERTABLEVIEW 80

#define APARIENCIAMASTERTABLEVIEW(BACKGROUNDVIEW,HEIGHTCELL) [[CustomCellAppearance alloc] initWithAppearanceWithCustomBackgroundViewWithSelectedColor:SELECTEDCOLORAPARIENCIAMASTERTABLEVIEW unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIAMASTERTABLEVIEW selectedTextColor:TEXTSELECTEDCOLORAPARIENCIAMASTERTABLEVIEW unselectedTextFont:UNSELECTEDFONTAPARIENCIAMASTERTABLEVIEW selectedTextFont:SELECTEDFONTAPARIENCIAMASTERTABLEVIEW textAlignment:TEXTALIGNMENTMASTERTABLEVIEW accesoryType:ACCESORYTYPEMASTERTABLEVIEW lineBreakMode:LINEBREAKMODEMASTERTABLEVIEW numberOfLines:NUMBEROFLINESMASTERTABLEVIEW accesoryView:ACCESORYVIEWMASTERTABLEVIEW backgroundView:BACKGROUNDVIEW heightCell:HEIGHTCELL]

#define UNSELECTEDCOLORAPARIENCIASALIR [UIColor redColor]
#define SELECTEDCOLORAPARIENCIASALIR [UIColor redColor]
#define TEXTUNSELECTEDCOLORAPARIENCIASALIR [UIColor whiteColor]
#define TEXTSELECTEDCOLORAPARIENCIASALIR [UIColor whiteColor]
#define UNSELECTEDFONTAPARIENCIASALIR [UIFont boldSystemFontOfSize:18.0]
#define SELECTEDFONTAPARIENCIASALIR [UIFont boldSystemFontOfSize:18.0]
#define BORDERCOLORSALIR [UIColor colorWithRed:(56/255.0) green:(115/255.0) blue:(194/255.0) alpha:1.0]
#define BORDERWIDTHSALIR 0.8
#define CORNERRADIUSSALIR 0
#define TEXTALIGNMENTSALIR NSTextAlignmentCenter
#define ACCESORYTYPESALIR UITableViewCellAccessoryNone
#define LINEBREAKMODESALIR NSLineBreakByWordWrapping
#define NUMBEROFLINESSALIR 0
#define ACCESORYVIEWSALIR nil
#define HEIGHTCELLSALIR 47

#define APARIENCIASALIR [[CustomCellAppearance alloc] initWithAppearanceWithUnselectedColor:UNSELECTEDCOLORAPARIENCIASALIR selectedColor:SELECTEDCOLORAPARIENCIASALIR unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIASALIR selectedTextColor:TEXTSELECTEDCOLORAPARIENCIASALIR unselectedTextFont:UNSELECTEDFONTAPARIENCIASALIR selectedTextFont:SELECTEDFONTAPARIENCIASALIR borderColor:BORDERCOLORSALIR borderWidth:BORDERWIDTHSALIR cornerRadius:CORNERRADIUSSALIR textAlignment:TEXTALIGNMENTSALIR accesoryType:ACCESORYTYPESALIR lineBreakMode:LINEBREAKMODESALIR numberOfLines:NUMBEROFLINESSALIR accesoryView:ACCESORYVIEWSALIR heightCell:HEIGHTCELLSALIR]


#define SELECTEDCOLORAPARIENCIALISTADOENLACES [UIColor colorWithRed:(133/255.0) green:(163/255.0) blue:(206/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIALISTADOENLACES nil
#define TEXTSELECTEDCOLORAPARIENCIALISTADOENLACES nil
#define UNSELECTEDFONTAPARIENCIALISTADOENLACES nil
#define SELECTEDFONTAPARIENCIALISTADOENLACES nil
#define TEXTALIGNMENTLISTADOENLACES 0
#define ACCESORYTYPELISTADOENLACES UITableViewCellAccessoryNone
#define LINEBREAKMODELISTADOENLACES 0
#define NUMBEROFLINESLISTADOENLACES 0
#define ACCESORYVIEWLISTADOENLACES nil
//#define CUSTOMHEIGHTCELLLISTADOENLACES 80

#define APARIENCIALISTADOENLACES(BACKGROUNDVIEW,HEIGHTCELL) [[CustomCellAppearance alloc] initWithAppearanceWithCustomBackgroundViewWithSelectedColor:SELECTEDCOLORAPARIENCIALISTADOENLACES unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIALISTADOENLACES selectedTextColor:TEXTSELECTEDCOLORAPARIENCIALISTADOENLACES unselectedTextFont:UNSELECTEDFONTAPARIENCIALISTADOENLACES selectedTextFont:SELECTEDFONTAPARIENCIALISTADOENLACES textAlignment:TEXTALIGNMENTLISTADOENLACES accesoryType:ACCESORYTYPELISTADOENLACES lineBreakMode:LINEBREAKMODELISTADOENLACES numberOfLines:NUMBEROFLINESLISTADOENLACES accesoryView:ACCESORYVIEWLISTADOENLACES backgroundView:BACKGROUNDVIEW heightCell:HEIGHTCELL]
/*
#define UNSELECTEDCOLORAPARIENCIA3 [UIColor whiteColor]
#define SELECTEDCOLORAPARIENCIA3 [UIColor colorWithRed:(71/255.0) green:(105/255.0) blue:(153/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIA3 [UIColor blackColor]
#define TEXTSELECTEDCOLORAPARIENCIA3 [UIColor whiteColor]
#define UNSELECTEDFONTAPARIENCIA3 [UIFont systemFontOfSize:16.0]
#define SELECTEDFONTAPARIENCIA3 [UIFont boldSystemFontOfSize:16.0]
#define BORDERCOLOR3 [UIColor blackColor]
#define BORDERWIDTH3 0.8
#define CORNERRADIUS3 8
#define TEXTALIGNMENT3 UITextAlignmentLeft
#define ACCESORYTYPE3 UITableViewCellAccessoryDisclosureIndicator
#define LINEBREAKMODE3 UILineBreakModeWordWrap
#define NUMBEROFLINES3 0
#define ACCESORYVIEW3 nil
#define HEIGHTCELL3 44

#define APARIENCIA3 [[CustomCellAppearance alloc] initWithAppearance:UNSELECTEDCOLORAPARIENCIA3 :SELECTEDCOLORAPARIENCIA3 :TEXTUNSELECTEDCOLORAPARIENCIA3 :TEXTSELECTEDCOLORAPARIENCIA3 :UNSELECTEDFONTAPARIENCIA3 :SELECTEDFONTAPARIENCIA3: BORDERCOLOR3: BORDERWIDTH3: CORNERRADIUS3: TEXTALIGNMENT3: ACCESORYTYPE3: LINEBREAKMODE3: NUMBEROFLINES3: ACCESORYVIEW3: HEIGHTCELL3]*/

@class CustomCell,CustomCellAppearance;
@interface FabricaCeldas : NSObject


+(FabricaCeldas *) getInstance;
-(void) createNewCustomCellWithAppearance:(CustomCellAppearance *) appearance cellText: (NSString *) cellText selectionType: (BOOL) selectionType customCell:(CustomCell *) customCell;
    
    /*-(CustomCell *) getNewCustomCell: (NSString *) cellText: (BOOL) selectionType;
-(CustomCell *) getNewCustomCellELMUNDO: (NSString *) cellText: (BOOL) selectionType;
-(CustomCell *) getNewCustomCell3: (NSString *) cellText: (BOOL) selectionType;*/
@end
