//
//  ListadoCapitulosPendientesViewController.h
//  Series ly iOS
//
//  Created by Lorenzo Villarroel Pérez on 27/04/13.
//  Copyright (c) 2013 lorenzo villarroel perez. All rights reserved.
//

#import "RefreshableViewController.h"

typedef enum {
    SourceSeriesPendientes,
    SourcePeliculasPendientes,
    SourceTVShowsPendientes,
    SourceDocumentalesPendientes,
}TipoSourceData;

@class CustomTableViewController;
@interface ListadoCapitulosPendientesViewController : RefreshableViewController


//@property (strong, nonatomic) CustomTableViewController *tableViewEpisodios;
@property (assign, nonatomic) CGRect frame;
@property (assign, nonatomic) TipoSourceData tipoSourceData;


- (id)initWithFrame: (CGRect) frame SourceData: (TipoSourceData) sourceData;
//- (void) fillTableViewFromSource: (NSMutableArray *) source;
- (void) reloadTableViewFromSource: (NSMutableArray *) source;


@end


#define SELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPAD [UIColor colorWithRed:(133/255.0) green:(163/255.0) blue:(206/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPAD nil
#define TEXTSELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPAD nil
#define UNSELECTEDFONTAPARIENCIALISTADOCAPITULOSIPAD nil
#define SELECTEDFONTAPARIENCIALISTADOCAPITULOSIPAD nil
#define TEXTALIGNMENTLISTADOCAPITULOSIPAD 0
#define ACCESORYTYPELISTADOCAPITULOSIPAD UITableViewCellAccessoryNone
#define LINEBREAKMODELISTADOCAPITULOSIPAD 0
#define NUMBEROFLINESLISTADOCAPITULOSIPAD 0
#define ACCESORYVIEWLISTADOCAPITULOSIPAD nil
//#define CUSTOMHEIGHTCELLLISTADOCAPITULOSIPAD 80

#define APARIENCIALISTADOCAPITULOSIPAD(BACKGROUNDVIEW,HEIGHTCELL) [[CustomCellAppearance alloc] initWithAppearanceWithCustomBackgroundViewWithSelectedColor:SELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPAD unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPAD selectedTextColor:TEXTSELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPAD unselectedTextFont:UNSELECTEDFONTAPARIENCIALISTADOCAPITULOSIPAD selectedTextFont:SELECTEDFONTAPARIENCIALISTADOCAPITULOSIPAD textAlignment:TEXTALIGNMENTLISTADOCAPITULOSIPAD accesoryType:ACCESORYTYPELISTADOCAPITULOSIPAD lineBreakMode:LINEBREAKMODELISTADOCAPITULOSIPAD numberOfLines:NUMBEROFLINESLISTADOCAPITULOSIPAD accesoryView:ACCESORYVIEWLISTADOCAPITULOSIPAD backgroundView:BACKGROUNDVIEW heightCell:HEIGHTCELL]

#define SELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPHONE [UIColor colorWithRed:(133/255.0) green:(163/255.0) blue:(206/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPHONE nil
#define TEXTSELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPHONE nil
#define UNSELECTEDFONTAPARIENCIALISTADOCAPITULOSIPHONE nil
#define SELECTEDFONTAPARIENCIALISTADOCAPITULOSIPHONE nil
#define TEXTALIGNMENTLISTADOCAPITULOSIPHONE 0
#define ACCESORYTYPELISTADOCAPITULOSIPHONE UITableViewCellAccessoryDisclosureIndicator
#define LINEBREAKMODELISTADOCAPITULOSIPHONE 0
#define NUMBEROFLINESLISTADOCAPITULOSIPHONE 0
#define ACCESORYVIEWLISTADOCAPITULOSIPHONE nil
//#define CUSTOMHEIGHTCELLLISTADOCAPITULOSIPHONE 80

#define APARIENCIALISTADOCAPITULOSIPHONE(BACKGROUNDVIEW,HEIGHTCELL) [[CustomCellAppearance alloc] initWithAppearanceWithCustomBackgroundViewWithSelectedColor:SELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPHONE unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPHONE selectedTextColor:TEXTSELECTEDCOLORAPARIENCIALISTADOCAPITULOSIPHONE unselectedTextFont:UNSELECTEDFONTAPARIENCIALISTADOCAPITULOSIPHONE selectedTextFont:SELECTEDFONTAPARIENCIALISTADOCAPITULOSIPHONE textAlignment:TEXTALIGNMENTLISTADOCAPITULOSIPHONE accesoryType:ACCESORYTYPELISTADOCAPITULOSIPHONE lineBreakMode:LINEBREAKMODELISTADOCAPITULOSIPHONE numberOfLines:NUMBEROFLINESLISTADOCAPITULOSIPHONE accesoryView:ACCESORYVIEWLISTADOCAPITULOSIPHONE backgroundView:BACKGROUNDVIEW heightCell:HEIGHTCELL]