//
//  AcercaDeViewController.h
//  Series ly iOS
//
//  Created by Lorenzo Villarroel Pérez on 20/05/13.
//  Copyright (c) 2013 lorenzo villarroel perez. All rights reserved.
//

#import "LoadableWithTableViewController.h"

@interface AcercaDeViewController : LoadableWithTableViewController

@property (assign, nonatomic) CGRect frame;

- (id)initWithFrame: (CGRect) frame;

@end
#define SELECTEDCOLORAPARIENCIAACERCADE [UIColor colorWithRed:(133/255.0) green:(163/255.0) blue:(206/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIAACERCADE nil
#define TEXTSELECTEDCOLORAPARIENCIAACERCADE nil
#define UNSELECTEDFONTAPARIENCIAACERCADE nil
#define SELECTEDFONTAPARIENCIAACERCADE nil
#define TEXTALIGNMENTACERCADE 0
#define ACCESORYTYPEACERCADE UITableViewCellAccessoryNone
#define LINEBREAKMODEACERCADE 0
#define NUMBEROFLINESACERCADE 0
#define ACCESORYVIEWACERCADE nil
//#define CUSTOMHEIGHTCELLACERCADE 80

#define APARIENCIAACERCADE(BACKGROUNDVIEW,HEIGHTCELL) [[CustomCellAppearance alloc] initWithAppearanceWithCustomBackgroundViewWithSelectedColor:SELECTEDCOLORAPARIENCIAACERCADE unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIAACERCADE selectedTextColor:TEXTSELECTEDCOLORAPARIENCIAACERCADE unselectedTextFont:UNSELECTEDFONTAPARIENCIAACERCADE selectedTextFont:SELECTEDFONTAPARIENCIAACERCADE textAlignment:TEXTALIGNMENTACERCADE accesoryType:ACCESORYTYPEACERCADE lineBreakMode:LINEBREAKMODEACERCADE numberOfLines:NUMBEROFLINESACERCADE accesoryView:ACCESORYVIEWACERCADE backgroundView:BACKGROUNDVIEW heightCell:HEIGHTCELL]

#define UNSELECTEDCOLORAPARIENCIAPERFILSELECCIONIPHONE [UIColor whiteColor]
#define SELECTEDCOLORAPARIENCIAPERFILSELECCIONIPHONE [UIColor colorWithRed:(133/255.0) green:(163/255.0) blue:(206/255.0) alpha:1]
#define TEXTUNSELECTEDCOLORAPARIENCIAPERFILSELECCIONIPHONE [UIColor blackColor]
#define TEXTSELECTEDCOLORAPARIENCIAPERFILSELECCIONIPHONE [UIColor blackColor]
#define UNSELECTEDFONTAPARIENCIAPERFILSELECCIONIPHONE [UIFont systemFontOfSize:18.0]
#define SELECTEDFONTAPARIENCIAPERFILSELECCIONIPHONE [UIFont systemFontOfSize:18.0]
#define BORDERCOLORPERFILSELECCIONIPHONE [UIColor colorWithRed:(213/255.0) green:(216/255.0) blue:(217/255.0) alpha:1.0]
#define BORDERWIDTHPERFILSELECCIONIPHONE 0.8
#define CORNERRADIUSPERFILSELECCIONIPHONE 0
#define TEXTALIGNMENTPERFILSELECCIONIPHONE NSTextAlignmentLeft
#define ACCESORYTYPEPERFILSELECCIONIPHONE UITableViewCellAccessoryNone
#define LINEBREAKMODEPERFILSELECCIONIPHONE NSLineBreakByWordWrapping
#define NUMBEROFLINESPERFILSELECCIONIPHONE 0
#define ACCESORYVIEWPERFILSELECCIONIPHONE nil
#define HEIGHTCELLPERFILSELECCIONIPHONE 68

#define APARIENCIAPERFILSELECCIONIPHONE [[CustomCellAppearance alloc] initWithAppearanceWithUnselectedColor:UNSELECTEDCOLORAPARIENCIAPERFILSELECCIONIPHONE selectedColor:SELECTEDCOLORAPARIENCIAPERFILSELECCIONIPHONE unselectedTextColor:TEXTUNSELECTEDCOLORAPARIENCIAPERFILSELECCIONIPHONE selectedTextColor:TEXTSELECTEDCOLORAPARIENCIAPERFILSELECCIONIPHONE unselectedTextFont:UNSELECTEDFONTAPARIENCIAPERFILSELECCIONIPHONE selectedTextFont:SELECTEDFONTAPARIENCIAPERFILSELECCIONIPHONE borderColor:BORDERCOLORPERFILSELECCIONIPHONE borderWidth:BORDERWIDTHPERFILSELECCIONIPHONE cornerRadius:CORNERRADIUSPERFILSELECCIONIPHONE textAlignment:TEXTALIGNMENTPERFILSELECCIONIPHONE accesoryType:ACCESORYTYPEPERFILSELECCIONIPHONE lineBreakMode:LINEBREAKMODEPERFILSELECCIONIPHONE numberOfLines:NUMBEROFLINESPERFILSELECCIONIPHONE accesoryView:ACCESORYVIEWPERFILSELECCIONIPHONE heightCell:HEIGHTCELLPERFILSELECCIONIPHONE]